apiVersion: v1
kind: Namespace
metadata:
  name: cosign-gatekeeper-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosign-gatekeeper-provider
  namespace: cosign-gatekeeper-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cosign-gatekeeper-provider
  template:
    metadata:
      labels:
        run: cosign-gatekeeper-provider
    spec:
      containers:
      - image: devopps/cosign-gatekeeper-provider:v1.0.0-ib
        imagePullPolicy: IfNotPresent
        name: cosign-gatekeeper-provider
        command:
          - /cosign-gatekeeper-provider
        args:
          - "--port=8090"
          - "--cert=/tls/cert.pem"
          - "--key=/tls/key.pem"
        ports:
        - containerPort: 8090
          protocol: TCP
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
